int validaAltura (float);
int validaPeso (float); 
float calcularIMC(float, float);
int validadeDataDeNascimento(int, int, int);
int ehDigito(char);
int validarMatr(char*);
int validarNome (char*);
int validaEmail (char*);
int ehValido(char);
void delay(int);
void limpaTela(void);
